### ISSUE TITLE
Dependency Deprecated

### ISSUE THREAD

**Issue by jrtechs** [FOSSRIT/lemonade-stand#33]
Hey, I just tried installing the dependencies for lemonade-stand. I got pygames, however, I couldn't find Fortune Engine. The link provided is a dead page now:
https://fedorahosted.org/fortune_hunter/wiki/FortuneEngine

Not sure who would be the best person to ask about this issue. @jwflory would you happen to know where I can find this dependency? I can update the readme after I get it running. I tried googling for this engine but, it doesn't appear to be very popular -- or at least anymore.

**Comment by justwheel** [comment]
@jrtechs Funny you mention this. It now lives here:

https://github.com/FOSSRIT/FortuneEngine

This repo could probably use a PR to point to the new git remote. This used to live in Fedora's infrastructure and I had to go ask the Fedora Infrastructure team to share a backup of this git repository with me. I pushed it up to the FOSSRIT GitHub org maybe a week or two ago.

**Comment by jrtechs** [comment]
Thanks @jwflory! I managed to install the fortune engine but am now having issues with sugar dependencies. I'm trying to run this without using the sugar VM because my laptop is not powerful enough. I'm digging through the sugar-docs however, I'm not finding any clear way to just install the sugar python dependencies. Any pointers?

```
pygame 1.9.5
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "LemonadeStand.py", line 4, in <module>
    from LemonadeMain import LemonadeMain
  File "/home/jeff/Documents/hfoss/lemonade-stand/LemonadeMain.py", line 31, in <module>
    from badges import badges
  File "/home/jeff/Documents/hfoss/lemonade-stand/badges.py", line 1, in <module>
    from sugar.datastore import datastore
ImportError: No module named sugar.datastore
```

**Comment by justwheel** [comment]
@jrtechs Looks like it is a dependency issue on [sugar-datastore](https://github.com/sugarlabs/sugar-datastore). The suggested fix is [installing the Sugar Desktop](https://github.com/sugarlabs/sugar). There are easy instructions for Debian, Ubuntu, and Fedora in that repo's README. If you're on another distro or operating system, you will have to find the equivalent packages.

I don't think there is an easy and fast way to do this that doesn't require either (1) installing the Sugar Desktop packages, or (2) using a VM with Sugar. If you're feeling creative, you could also try containers just to figure out what it takes to get it to successfully start.
